// ============================================================
// 盈利项目数据 — 来自 TrustMRR.com 公开验证数据
// 6大应用赛道分类
// ============================================================

const trackMeta = {
    hosting:   { icon: '🏠', label: '托管部署', color: '#6366f1', desc: '一键部署 OpenClaw，按月收费' },
    install:   { icon: '🔧', label: '安装服务', color: '#10b981', desc: '为客户远程或线下安装配置' },
    template:  { icon: '📦', label: '模板/Wrapper', color: '#f97316', desc: '开发模板或封装工具出售' },
    training:  { icon: '🎓', label: '培训教育', color: '#ec4899', desc: '教别人使用 OpenClaw' },
    marketplace: { icon: '🛒', label: '技能市场', color: '#8b5cf6', desc: '开发/销售 AI 技能插件' },
    saas:      { icon: '🤖', label: 'SaaS 产品', color: '#0ea5e9', desc: '基于 OpenClaw 构建 SaaS' },
};

const profitProjects = [
    {
        name: 'Claw Mart',
        desc: '销售实战验证的 AI 配置方案 — Playbook、工具设置、分步指南，跳过繁琐的 Prompt 工程。',
        revenue30d: 85000,
        mrr: 3900,
        totalRevenue: 85000,
        track: 'marketplace',
        url: 'https://trustmrr.com/startup/claw-mart',
        highlight: '配置方案出售，利润率极高',
    },
    {
        name: 'OpenClaw Pro',
        desc: '最快上手 OpenClaw 的方式——一键部署你的专属实例，无需任何技术基础。',
        revenue30d: 52000,
        mrr: 57000,
        totalRevenue: 53000,
        track: 'hosting',
        url: 'https://trustmrr.com/startup/openclaw-pro',
        highlight: 'MRR $57k，持续被动收入',
    },
    {
        name: 'Roofclaw',
        desc: '预装 OpenClaw 的 MacBook Air，含一对一培训和每周支持。专注屋顶行业但不限于此。',
        revenue30d: 50000,
        mrr: 0,
        totalRevenue: 1800000,
        track: 'install',
        url: 'https://trustmrr.com/startup/roofclaw',
        highlight: '累计 $1.8M！硬件+服务模式',
    },
    {
        name: 'Donely',
        desc: '一键云端部署 OpenClaw，24/7 在线。一键 WhatsApp 设置，BYOK 自带密钥。',
        revenue30d: 44000,
        mrr: 2700,
        totalRevenue: 747000,
        track: 'hosting',
        url: 'https://trustmrr.com/startup/donely',
        highlight: '累计 $747k，云托管赛道领跑者',
    },
    {
        name: 'setupclaw',
        desc: '专业 OpenClaw 安装服务，可选搭配 Mac Mini 硬件。纯服务模式。',
        revenue30d: 43000,
        mrr: 0,
        totalRevenue: 50000,
        track: 'install',
        url: 'https://trustmrr.com/startup/setupclaw',
        highlight: '纯安装服务月入 $43k',
    },
    {
        name: 'AI MONEY GROUP',
        desc: '帮客户搭建 OpenClaw 并将 AI 员工（AI Personas）部署给企业主。',
        revenue30d: 18000,
        mrr: 13000,
        totalRevenue: 288000,
        track: 'training',
        url: 'https://trustmrr.com/startup/ai-money-group',
        highlight: '培训赛道标杆，累计 $288k',
    },
    {
        name: 'StartClaw',
        desc: 'AI 生产力追踪软件，帮助个人和企业提升效率。',
        revenue30d: 11000,
        mrr: 7400,
        totalRevenue: 14000,
        track: 'saas',
        url: 'https://trustmrr.com/startup/startclaw',
        highlight: 'SaaS 模式，MRR $7.4k',
    },
    {
        name: 'OpenClaw Kit',
        desc: '几分钟内发布你的 OpenClaw Wrapper。基于 TurboStarter 构建。',
        revenue30d: 8400,
        mrr: 0,
        totalRevenue: 42000,
        track: 'template',
        url: 'https://trustmrr.com/startup/openclaw-kit',
        highlight: '模板出售累计 $42k',
    },
    {
        name: 'Quick Claw',
        desc: '30秒内在手机上使用 OpenClaw。一个 App 搞定，无需 API Key。',
        revenue30d: 8300,
        mrr: 5800,
        totalRevenue: 10000,
        track: 'saas',
        url: 'https://trustmrr.com/startup/quick-claw',
        highlight: '移动端 SaaS，MRR $5.8k',
    },
    {
        name: 'Coral',
        desc: '最丝滑的 OpenClaw 部署方式，自动化你的工作流。',
        revenue30d: 7800,
        mrr: 16000,
        totalRevenue: 7900,
        track: 'hosting',
        url: 'https://trustmrr.com/startup/coral',
        highlight: 'MRR $16k，增长最快',
    },
    {
        name: 'AtomicBot.ai',
        desc: '最快的 OpenClaw 运行方式——云端或本地。Mac/Win/iOS/Android 全平台覆盖。',
        revenue30d: 7700,
        mrr: 4900,
        totalRevenue: 7700,
        track: 'saas',
        url: 'https://trustmrr.com/startup/atomicbot-ai',
        highlight: '全平台 SaaS',
    },
    {
        name: 'ClawWrapper',
        desc: '快速发布你的 OpenClaw Wrapper 产品。',
        revenue30d: 7400,
        mrr: 0,
        totalRevenue: 18000,
        track: 'template',
        url: 'https://trustmrr.com/startup/clawwrapper',
        highlight: '模板赛道累计 $18k',
    },
    {
        name: 'OpenTweet',
        desc: 'AI 驱动的 X(Twitter) 帖子调度器，集成 MCP 和 OpenClaw。',
        revenue30d: 7300,
        mrr: 1100,
        totalRevenue: 7800,
        track: 'saas',
        url: 'https://trustmrr.com/startup/opentweet',
        highlight: '垂直 SaaS 应用',
    },
    {
        name: 'LarryBrain',
        desc: 'OpenClaw 高级技能市场，利润率极高，主要成本仅为托管和存储。',
        revenue30d: 6700,
        mrr: 6800,
        totalRevenue: 6700,
        track: 'marketplace',
        url: 'https://trustmrr.com/startup/larrybrain-openclaw-marketplace',
        highlight: '技能市场，极高利润率',
    },
    {
        name: 'Agent 37',
        desc: '创建和管理你的 OpenClaw 智能体。',
        revenue30d: 4500,
        mrr: 4100,
        totalRevenue: 11000,
        track: 'saas',
        url: 'https://trustmrr.com/startup/agent-37',
        highlight: '智能体管理平台',
    },
    {
        name: 'Clawhosters.com',
        desc: '托管 OpenClaw，即时部署、零维护、多平台支持。',
        revenue30d: 3300,
        mrr: 3400,
        totalRevenue: 3300,
        track: 'hosting',
        url: 'https://trustmrr.com/startup/clawhosters-com',
        highlight: '托管服务稳定收入',
    },
];

// 汇总统计
const profitStats = {
    totalRevenue30d: 389331,
    totalProjects: 159,
    topTotalRevenue: 1800000,
    topMRR: 57000,
};
