// ============================================================
// OpenClaw 热门技能库 — 分类 + 安全评估 + 应用场景
// ============================================================
const skillCategories = [
    { id: 'automation', icon: '⚙️', label: '工作流自动化' },
    { id: 'browser', icon: '🌐', label: '浏览器 & 爬虫' },
    { id: 'content', icon: '✍️', label: '内容生成' },
    { id: 'productivity', icon: '📊', label: '办公生产力' },
    { id: 'dev', icon: '💻', label: '开发工具' },
    { id: 'finance', icon: '💰', label: '金融 & Web3' },
    { id: 'system', icon: '🔒', label: '系统 & 安全' },
];

// safetyLevel: 'safe' | 'caution' | 'warning'
// safe = 零依赖/官方维护/纯 Markdown Skill
// caution = 需要外部 API / 需要授权
// warning = 需要高权限 / 第三方来源 / 需仔细审查
const skillsData = [
    // ====== 工作流自动化 ======
    {
        name: 'n8n-workflow-automation',
        title: 'n8n 工作流自动化',
        desc: '让 OpenClaw 与 n8n 联动，实现邮件、Notion、Trello、钉钉等办公工具自动同步，无需编码即可构建自动化流程。',
        category: 'automation',
        safetyLevel: 'caution',
        safetyNote: '需要 n8n 服务端，API 密钥需妥善保管。仅授权必需的工作流权限。',
        moneyTip: '可为企业搭建自动化工作流，按项目收费 ¥1000-5000/个。',
        source: 'ClawHub',
        tags: ['n8n', '办公自动化', '零代码'],
    },
    {
        name: 'automation-workflows',
        title: '自动化编排器',
        desc: '帮助 Agent 设计跨工具自动化流程：触发器→动作→条件分支。把高重复低价值工作交给 AI。',
        category: 'automation',
        safetyLevel: 'safe',
        safetyNote: '纯 Markdown Skill，无外部依赖，安全性高。',
        moneyTip: '设计并出售行业自动化模板（如电商客服流程），每套 ¥200-500。',
        source: 'ClawHub',
        tags: ['编排', '模板', '自动化'],
    },
    {
        name: 'composio',
        title: 'Composio 860+ 工具集成',
        desc: '一个集成框架接入 860+ 外部工具（GitHub/Slack/Gmail/Salesforce 等），无需逐个编写认证管道。',
        category: 'automation',
        safetyLevel: 'caution',
        safetyNote: '功能强大但权限范围广。建议仅启用实际需要的工具连接器，定期审查 OAuth 授权。',
        moneyTip: '为企业搭建多工具集成方案，按集成数量和复杂度收费。',
        source: 'Composio',
        tags: ['集成', '860+工具', 'OAuth'],
    },

    // ====== 浏览器 & 爬虫 ======
    {
        name: 'playwright-scraper',
        title: 'Playwright 智能爬虫',
        desc: '抓取 JavaScript 密集型或有反爬保护的网站。支持截图、PDF、结构化数据提取。',
        category: 'browser',
        safetyLevel: 'caution',
        safetyNote: '需安装 Playwright 运行时。注意遵守目标网站 robots.txt 和服务条款。',
        moneyTip: '提供竞品数据监控服务，按月订阅 ¥500-2000。',
        source: 'ClawHub',
        tags: ['爬虫', '反反爬', '数据采集'],
    },
    {
        name: 'exa-web-search',
        title: 'Exa 结构化搜索',
        desc: '为开发者设计的搜索引擎，从 GitHub/技术文档/论坛精准提取信息，大幅减少 AI 幻觉。',
        category: 'browser',
        safetyLevel: 'safe',
        safetyNote: '只读搜索操作，不修改任何数据。需要 Exa API Key（有免费额度）。',
        moneyTip: '用于自动化市场研究报告，每份报告收费 ¥100-300。',
        source: 'Composio',
        tags: ['搜索', '开发者', '精准'],
    },
    {
        name: 'tavily-web-search',
        title: 'Tavily AI 搜索引擎',
        desc: '专为 AI Agent 优化的搜索 API，直接返回精简高相关结果，突破 LLM 知识时效性限制。',
        category: 'browser',
        safetyLevel: 'safe',
        safetyNote: '纯搜索 API，安全性高。有每月免费搜索额度。',
        moneyTip: '构建实时信息监控 Agent，按行业定制出售。',
        source: 'ClawHub',
        tags: ['AI搜索', '实时', '免费额度'],
    },

    // ====== 内容生成 ======
    {
        name: 'summariz',
        title: '智能摘要生成器',
        desc: '自动提炼 PDF、学术论文、会议录音、长篇文章的核心要点，支持多格式输入。',
        category: 'content',
        safetyLevel: 'safe',
        safetyNote: '纯文本处理，不上传数据到第三方服务器。安全性极高。',
        moneyTip: '提供论文/报告精读服务，每篇 ¥50-200。',
        source: 'ClawHub',
        tags: ['摘要', 'PDF', '论文'],
    },
    {
        name: 'bird-writer',
        title: 'Bird 风格化写作',
        desc: '学习你的写作风格后自动撰写帖子/文章。支持多平台（推特/公众号/知乎）的风格适配。',
        category: 'content',
        safetyLevel: 'safe',
        safetyNote: '纯 Markdown Skill，无外部依赖。内容生成后建议人工审核再发布。',
        moneyTip: '自动化内容矩阵运营，通过广告/赞助/课程销售变现。',
        source: 'ClawHub',
        tags: ['写作', '风格学习', '自媒体'],
    },
    {
        name: 'bilibili-danmaku',
        title: 'B站弹幕分析',
        desc: 'B站弹幕抓取+词云生成+情感分析+舆情报告输出。国内创作者必备分析工具。',
        category: 'content',
        safetyLevel: 'caution',
        safetyNote: '需要访问 B站 API。注意 API 调用频率限制，避免被封。',
        moneyTip: 'B站品牌口碑分析服务，每次 ¥300-1000。',
        source: 'ClawHub',
        tags: ['B站', '弹幕', '舆情分析'],
    },

    // ====== 办公生产力 ======
    {
        name: 'gog-google-workspace',
        title: 'Google Workspace 全套',
        desc: '一站式接入 Gmail、日历、云端硬盘、表格、文档。AI 自动处理邮件、安排日程、管理文件。',
        category: 'productivity',
        safetyLevel: 'caution',
        safetyNote: '需要 Google OAuth 授权。建议使用最小权限范围，仅授权必需的 API scope。',
        moneyTip: '企业 AI 办公助理搭建，含培训和维护，年费 ¥5000-20000。',
        source: 'ClawHub',
        tags: ['Gmail', '日历', '文档', 'Google'],
    },
    {
        name: 'excel-wizard',
        title: 'Excel 魔法师',
        desc: '专注 Excel 操作的办公自动化工具。自动生成报表、数据透视、公式编写、批量处理。',
        category: 'productivity',
        safetyLevel: 'safe',
        safetyNote: '本地文件操作，不需要联网。注意备份重要 Excel 文件后再让 AI 操作。',
        moneyTip: '提供 Excel 自动化咨询和定制脚本，按项目收费。',
        source: 'ClawHub',
        tags: ['Excel', '报表', '批量处理'],
    },
    {
        name: 'daily-brief',
        title: '每日简报助手',
        desc: '每天自动汇总日历、天气、待办任务、新闻摘要。Token 成本极低，让 OpenClaw 更像真正的助理。',
        category: 'productivity',
        safetyLevel: 'safe',
        safetyNote: '轻量级 Skill，Token 消耗低。建议定制内容源以控制成本。',
        moneyTip: '定制行业日报服务（如科技/金融/电商），通过订阅变现。',
        source: 'Reddit 社区',
        tags: ['日报', '低成本', '自动化'],
    },
    {
        name: 'memory-search',
        title: '记忆语义搜索',
        desc: '对 OpenClaw 不断增长的记忆文件进行语义搜索，高效找到相关上下文。长期用户必装。',
        category: 'productivity',
        safetyLevel: 'safe',
        safetyNote: '纯本地操作，数据不出设备。安全性极高。',
        moneyTip: '构建企业知识库搜索方案，结合 RAG 按项目收费。',
        source: 'Reddit 社区',
        tags: ['记忆', '搜索', '本地'],
    },

    // ====== 开发工具 ======
    {
        name: 'github-skill',
        title: 'GitHub 集成',
        desc: '管理代码仓库、Issue、PR 和 Commit。AI 自动创建 Issue、审查代码变更、搜索代码。',
        category: 'dev',
        safetyLevel: 'caution',
        safetyNote: '需要 GitHub Token。建议使用 Fine-grained PAT，仅授权必需仓库的最小权限。',
        moneyTip: '自动化代码审查服务 + PR 管理机器人，按团队规模月费。',
        source: 'ClawHub 官方',
        tags: ['GitHub', '代码审查', 'PR'],
    },
    {
        name: 'reverse-engineering',
        title: '逆向工程分析',
        desc: '把 OpenClaw 变成网络分析师：抓包、解码二进制协议、生成解析器和文档。',
        category: 'dev',
        safetyLevel: 'warning',
        safetyNote: '⚠️ 高权限操作。需要网络抓包权限。仅在受控环境中使用，注意法律合规。',
        moneyTip: 'API 逆向分析和协议文档编写服务。',
        source: 'Composio',
        tags: ['逆向', '抓包', '协议分析'],
    },
    {
        name: 'self-improving-agent',
        title: '自进化 Agent',
        desc: '让 OpenClaw 记录错误、学习偏好、自我优化。越用越聪明，越来越个性化。',
        category: 'dev',
        safetyLevel: 'safe',
        safetyNote: '纯 Markdown Skill，仅修改本地日志文件。安全性高。',
        moneyTip: '将自进化机制封装为付费 Skill 出售。',
        source: 'Composio',
        tags: ['自学习', '个性化', '优化'],
    },
    {
        name: 'surrealdb-skill',
        title: 'SurrealDB 图数据库助手',
        desc: '专为 AI Agent 设计的图数据库集成。支持图查询、向量搜索、数据建模。构建本地知识库的核心。',
        category: 'dev',
        safetyLevel: 'caution',
        safetyNote: '需要安装 SurrealDB。数据库操作需注意权限控制。',
        moneyTip: '企业知识图谱搭建服务。',
        source: 'ClawHub',
        tags: ['数据库', '向量搜索', '知识图谱'],
    },

    // ====== 金融 & Web3 ======
    {
        name: 'trenchclaw',
        title: 'TrenchClaw Web3 助手',
        desc: 'Solana 链上智能助手——链上查询、合约交互、资产监控和链上自动化任务执行。',
        category: 'finance',
        safetyLevel: 'warning',
        safetyNote: '⚠️ 涉及资金操作！请务必使用独立钱包，不要放入大额资金。确认每笔交易。',
        moneyTip: 'Web3 自动化交易/套利/空投工具开发。',
        source: 'ClawHub',
        tags: ['Solana', 'Web3', '链上'],
    },

    // ====== 系统 & 安全 ======
    {
        name: 'credential-manager',
        title: '凭证管理器',
        desc: '集中管理所有 API 密钥和密码，自动设置文件权限。保护你的敏感信息。',
        category: 'system',
        safetyLevel: 'safe',
        safetyNote: '安全基础设施 Skill，强烈建议所有用户安装。',
        moneyTip: '集成到企业部署服务中，提升安全等级的增值服务。',
        source: 'ClawHub 官方',
        tags: ['安全', 'API密钥', '权限管理'],
    },
];
